apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: web-app-portfolio
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app-portfolio
    spec:
      containers:
      - name: postgres
        image: franklyn27181/altschool:2.0
        envFrom:
        - configMapRef:
            name: postgres-env
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
        volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
