apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
  namespace: web-app
  labels:
    name: web-app
    apps: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dep
  template:
    metadata:
      labels:
        app: web-dep
    spec:
      containers:
        - name: web-dep
          image: httpd
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
