apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dev
  namespace: web-app
  labels:
    name: web-app
    apps: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dev
  template:
    metadata:
      labels:
        app: web-dev
    spec:
      containers:
        - name: web-dep
          image: nginx
          ports:
            - containerPort: 80
#      volumes:
#        - name: nginx-conf
#          configMap:
#            name: nginx-conf
