apiVersion: v1
kind: Service
metadata:
  name: portfolio
spec:
  selector:
    app: web-app-portfolio
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
