apiVersion: v1
kind: Service
metadata:
  name: portfolio-ap
  namespace: web-app
spec:
  selector:
    app: web-dev
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
