apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  namespace: web-app
  labels:
    name: web-app
    apps: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-portfolio
  template:
    metadata:
      labels:
        app: web-app-portfolio
    spec:
      containers:
        - name: web-app-portfolio
          image: nginx
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
