name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  deploy-application:
    runs-on: ubuntu-latest
    steps:
      - run: sh "hi"
      - run: sh "hello-world"
