#name: deploy-kubernetes-using-github-actions
#run-name: ${{ github.actor }} is learning GitHub Actions
#on: [push]
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Install civo
#        uses: civo/action-civo@v1.0.0
#        with: 
#          token: ${{ secrets.CIVO_TOKEN }}
#      - name: save civo kubeconfig
#        run: civo kubernetes config my-k8s-cluster
#      - name: Create kubeconfig
#        run: |
#          mkdir ${HOME}/.kube
#          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        #  cat ${HOME}/.kube/config

#      - name: Deploy to K8s
#        run: kubectl apply -f portfolio/
        
