name: deploy-kubernetes-using-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env: 
 ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install civo
        uses: civo/action-civo@v1.0.0
        with: 
          token: ${{ secrets.CIVO_TOKEN }}
      - name: set the civo region
        run: civo region current FRA1
#      - name: Add api key
#        run: civo apikey add api-token 
      - name: save civo kubeconfig and specify the region
        run: civo kubernetes config my-k8s-cluster --save --region FRA1
      - name: Deploy to K8s
        run: kubectl delete deploy -n web-app web-dev
      - name: deploy the web app to k8s
        run: kubectl apply -f portfolio/postgres.yaml
      - name: deploy postgresdb
        run: kubectl apply -f portfolio/postgres-config.yaml
      - name: Deploy sock app
        run: kubectl apply -f complete-demo.yaml
      - name: monitor sock using prometheus
        run: kubectl apply -f deploy/kubernetes/manifests-monitoring
