name: deploy-kubernetes-using-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env: 
 ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install civo
        uses: civo/action-civo@v1.0.0
        with: 
          token: ${{ secrets.CIVO_TOKEN }}
      - name: set the civo region
        run: civo region current FRA1
#      - name: Add api key
#        run: civo apikey add api-token 
      - name: save civo kubeconfig and specify the region
        run: civo kubernetes config my-k8s-cluster --save --region FRA1
#      - name: save cluster authentication details
#      - run: |
#          civo k3s config github-ci-${{github.sha}} --save --local-path ~/.kube/config -y
#      - name: ensure we can connect to the api
#        run: |
#          i=0;
#          while [ $i -le 120 ]; do
#            kubectl get nodes && break;
#            ((i++));
#            sleep 1;
#          done 
      - name: Deploy to K8s
        run: kubectl apply -f portfolio/

